// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: tests/tpl/index.gohtml

package tpl

import (
	gorazor "github.com/sipin/gorazor/runtime"
	"github.com/sipin/gorazor/tests/data"
	"io"
	"strings"
)

// Index generates tests/tpl/index.gohtml
func Index(rows []data.BenchRow) string {
	var _b strings.Builder
	RenderIndex(&_b, rows)
	return _b.String()
}

// RenderIndex render tests/tpl/index.gohtml
func RenderIndex(_buffer io.StringWriter, rows []data.BenchRow) {
	// Line: 5
	_buffer.WriteString("<html>\n\t<head><title>test</title></head>\n\t<body>\n\t\t<ul>\n\t\t")
	for _, row := range rows {
		if row.Print {

			// Line: 12
			_buffer.WriteString("<li>ID=")
			// Line: 12
			_buffer.WriteString(gorazor.HTMLEscInt(row.ID))
			// Line: 12
			_buffer.WriteString(", Message=")
			// Line: 12
			_buffer.WriteString(gorazor.HTMLEscStr(row.Message))
			// Line: 12
			_buffer.WriteString("</li>")

		}
	}
	// Line: 15
	_buffer.WriteString("\n\t\t</ul>\n\t</body>\n</html>")

}
